# Generated by Django 5.0.6 on 2024-05-11 21:17

from django.db import migrations

def populate_roles(apps, schema_editor):
    entries = {
        'developer': 'the person on the team who works on issues',
        'product owner': 'the person on the team who writes issues',
        'scrum master': 'the teams coach',
    }
    Role = apps.get_model('accounts', 'Role')
    for key, value in entries.items():
        role_obj = Role(name=key, description=value)
        role_obj.save()

def populate_teams(apps, schema_editor):
    entries  = {
        'alpha': ' thea A team',
        'beta': 'the B team',
        'charlie': 'the C team',
    }
    Team = apps.get_model('accounts', 'Team')
    for key, value in entries.items():
        team_obj = Team(name=key, description=value)
        team_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_roles),
        migrations.RunPython(populate_teams),
    ]

